<a href="https://colab.research.google.com/github/TetianaMar-888/Python_for_ds_tasks/blob/main/Marinoshenko_Tetiana_HW7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [ ]:
!pip show numpy

In [6]:
import numpy as np
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [19]:
arr = np.array([5, 15, 25, 35, 45])
print(arr)
arr0 = np.zeros(7) #([0, 0, 0, 0, 0, 0, 0]) - без коми не можна, а якщо з комою то нулі з комою так і виводяться. Чому?
print(arr0)
arr1 = np.ones(6)
print(arr1)
arr_num = np.arange(10, 20)
print(arr_num)

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [31]:
arr = np.array([12, 24, 36, 48, 60])
arr_mul = arr * 2 #Помножте всі елементи на 2
print(arr_mul)
arr_add = arr + 10 #Додайте до всіх елементів 10
print(arr_add)
arr_sq = arr ** 2 #Піднесіть всі елементи до квадрату
print(arr_sq)
arr_sqrt = np.sqrt(arr) #Обчисліть квадратний корінь з усіх елементів
print(arr_sqrt)

[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [33]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
data

array([18, 27, 33, 41, 52, 68, 79])

In [40]:
data_mean = np.mean(data)
print(data_mean)
data_min = np.min(data)
print(data_min)
data_max = np.max(data)
print(data_max)
data_sum = np.sum(data)
print(data_sum)

45.42857142857143
18
79
318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [47]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(arr[0]) # Перший елемент
print(arr[-1]) # Останній елемент
print(arr[1:4]) # Елементи з індексами від 1 до 3
mask = arr > 40
print(arr[mask])# Елементи більші за 40

15
67
[22 35 44]
[44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [48]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [64]:
print(matrix.shape) # Форма матриці 3 рядки, 3 колонки
print(matrix[0]) # Перший рядок
print(matrix[:, 1]) # Друга колонка
print(np.sum(matrix)) # Сума всіх елементів
print(np.mean(matrix)) # Середнє всіх елементів

(3, 3)
[2 4 6]
[ 4 10 16]
90
10.0
