### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
vector = np.random.rand (10)
v = np.round(vector, 2)
print(v)

[0.79 0.89 0.73 0.37 0.08 0.39 0.95 0.65 0.15 0.03]


In [4]:
for value in v:
    print(value)

0.79
0.89
0.73
0.37
0.08
0.39
0.95
0.65
0.15
0.03


In [5]:
#створення вектора-стовпця v
v_value = v.reshape (10, 1)
#створення матриці m
m = np.array ([[11, 14, 17],
               [20, 23, 26],
               [29, 32, 35]])

print("Вектор стовбець v")
print(v_value)
print("\nМатриця m:")
print(m)

Вектор стовбець v
[[0.79]
 [0.89]
 [0.73]
 [0.37]
 [0.08]
 [0.39]
 [0.95]
 [0.65]
 [0.15]
 [0.03]]

Матриця m:
[[11 14 17]
 [20 23 26]
 [29 32 35]]


In [6]:
v, v.shape, m, m.shape

(array([0.79, 0.89, 0.73, 0.37, 0.08, 0.39, 0.95, 0.65, 0.15, 0.03]),
 (10,),
 array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [7]:
v_10 = v_value + 10
print(v_10)

[[10.79]
 [10.89]
 [10.73]
 [10.37]
 [10.08]
 [10.39]
 [10.95]
 [10.65]
 [10.15]
 [10.03]]


In [8]:
v_10.shape

(10, 1)

In [9]:
# множення матриці m на константу 2
m_mult_const = m * 2
print(m_mult_const)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [10]:
# новий вектор, який містить квадрат кожного vector
v_square = v_10 ** 2
print(v_square)

[[116.4241]
 [118.5921]
 [115.1329]
 [107.5369]
 [101.6064]
 [107.9521]
 [119.9025]
 [113.4225]
 [103.0225]
 [100.6009]]


In [11]:
v_square, v_square.shape

(array([[116.4241],
        [118.5921],
        [115.1329],
        [107.5369],
        [101.6064],
        [107.9521],
        [119.9025],
        [113.4225],
        [103.0225],
        [100.6009]]),
 (10, 1))


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [34]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

#1

In [13]:
E = np.dot(A, B)
print(E)

[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]


In [14]:
#варіант 2*2 матриці, якщо скорочуємо кінцеву матрицю result_matrix
E_2X2_2 = E[:2, :2]
print(E_2X2_2)

[[0.232  0.1627]
 [0.3061 0.4867]]


In [15]:
A, A.shape, B, B.shape, E, E.shape

(array([[0.18, 0.53],
        [0.75, 0.47],
        [0.35, 0.21]]),
 (3, 2),
 array([[0.17, 0.58, 0.75],
        [0.38, 0.11, 0.15]]),
 (2, 3),
 array([[0.232 , 0.1627, 0.2145],
        [0.3061, 0.4867, 0.633 ],
        [0.1393, 0.2261, 0.294 ]]),
 (3, 3))

In [16]:
A_2x2 = A[:2, :2]
print(A_2x2)

[[0.18 0.53]
 [0.75 0.47]]


In [17]:
B_2x2 = B[:2, :2]
print(B_2x2)

[[0.17 0.58]
 [0.38 0.11]]


In [18]:
# варіант, коли приводимо до вигляду 2*2 начаткові матриці, які будемо перемножати, щоб отримати result_matrix
E_2X2 = np.dot(A_2x2, B_2x2)
print(E_2X2)

[[0.232  0.1627]
 [0.3061 0.4867]]


# 2
Розмірність матриці при множенні на вектор С буде

In [19]:
Result_matrix = np.dot(E_2X2, C)
print(Result_matrix)

[[0.1627]
 [0.4867]]


In [20]:
E_2X2.shape, C.shape, Result_matrix.shape

((2, 2), (2, 1), (2, 1))

#3

In [36]:
D, D.shape, Result_matrix, Result_matrix.shape

(array([[0, 1],
        [1, 0]]),
 (2, 2),
 array([[0.1627],
        [0.4867]]),
 (2, 1))

In [43]:
Result_matrix_D = np.dot(Result_matrix, D)
print(Result_matrix_D)

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [37]:
Result_matrix_D = np.dot(D, Result_matrix)
print(Result_matrix_D)

[[0.4867]
 [0.1627]]


In [38]:
D.shape, Result_matrix_D.shape

((2, 1), (2, 2))


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [39]:
Result_matrix_D, Result_matrix_D.shape

(array([[0.4867],
        [0.1627]]),
 (2, 1))

#1

In [40]:
# Транспонування
Result_matrix_D.T, Result_matrix_D.T.shape

(array([[0.4867, 0.1627]]), (1, 2))

#2

In [28]:
#транспонування вектора vector

In [41]:
v.T, v.T.shape

(array([0.79, 0.89, 0.73, 0.37, 0.08, 0.39, 0.95, 0.65, 0.15, 0.03]), (10,))

якщо вектор горизонтальний, то в мене не змінилось нічого

#3

In [42]:
column_v = np.expand_dims(v, axis=1)

print("v:", v)
print("v.shape:", v.shape)

print("\ncolumn_v:\n", column_v)
print("column_v.shape:", column_v.shape)

v: [0.79 0.89 0.73 0.37 0.08 0.39 0.95 0.65 0.15 0.03]
v.shape: (10,)

column_v:
 [[0.79]
 [0.89]
 [0.73]
 [0.37]
 [0.08]
 [0.39]
 [0.95]
 [0.65]
 [0.15]
 [0.03]]
column_v.shape: (10, 1)


In [44]:
column_v, v

(array([[0.79],
        [0.89],
        [0.73],
        [0.37],
        [0.08],
        [0.39],
        [0.95],
        [0.65],
        [0.15],
        [0.03]]),
 array([0.79, 0.89, 0.73, 0.37, 0.08, 0.39, 0.95, 0.65, 0.15, 0.03]))

In [45]:
# Транспонування column_v
column_v_T = column_v.T

print("column_v_T:\n", column_v_T)
print("column_v_T.shape:", column_v_T.shape)

column_v_T:
 [[0.79 0.89 0.73 0.37 0.08 0.39 0.95 0.65 0.15 0.03]]
column_v_T.shape: (1, 10)
